 const cadastrosLeads = [
    {
        "id": 1,
        "comercio": "Loja A",
        "segmento": "Alimentação",
        "representante_ba": "Rep A",
        "responsável": "João Silva",
        "contato": "1234-5678",
        "instagram": "@loja_a",
        "cidade": "Santo André",
        "bairro": "Centro",
        "rua": "Rua das Flores, 123",
        "cep": "09010-000"
    },
    {
        "id": 2,
        "comercio": "Loja B",
        "segmento": "Roupas",
        "representante_ba": "Rep B",
        "responsável": "Maria Souza",
        "contato": "2345-6789",
        "instagram": "@loja_b",
        "cidade": "São Bernardo do Campo",
        "bairro": "Rudge Ramos",
        "rua": "Avenida Kennedy, 456",
        "cep": "09726-260"
    },
    {
        "id": 3,
        "comercio": "Loja C",
        "segmento": "Tecnologia",
        "representante_ba": "Rep C",
        "responsável": "Pedro Santos",
        "contato": "3456-7890",
        "instagram": "@loja_c",
        "cidade": "São Caetano do Sul",
        "bairro": "Santa Paula",
        "rua": "Rua Visconde de Inhaúma, 789",
        "cep": "09540-300"
    },
    {
        "id": 4,
        "comercio": "Loja D",
        "segmento": "Beleza",
        "representante_ba": "Rep D",
        "responsável": "Ana Oliveira",
        "contato": "4567-8901",
        "instagram": "@loja_d",
        "cidade": "Santo André",
        "bairro": "Jardim",
        "rua": "Rua das Acácias, 101",
        "cep": "09190-300"
    },
    {
        "id": 5,
        "comercio": "Loja E",
        "segmento": "Educação",
        "representante_ba": "Rep E",
        "responsável": "Carlos Pereira",
        "contato": "5678-9012",
        "instagram": "@loja_e",
        "cidade": "São Bernardo do Campo",
        "bairro": "Centro",
        "rua": "Avenida Lucas Nogueira Garcez, 202",
        "cep": "09715-000"
    },
    {
        "id": 6,
        "comercio": "Loja F",
        "segmento": "Esportes",
        "representante_ba": "Rep F",
        "responsável": "Paula Lima",
        "contato": "6789-0123",
        "instagram": "@loja_f",
        "cidade": "São Caetano do Sul",
        "bairro": "Centro",
        "rua": "Rua Amazonas, 303",
        "cep": "09520-070"
    },
    {
        "id": 7,
        "comercio": "Loja G",
        "segmento": "Automotivo",
        "representante_ba": "Rep G",
        "responsável": "Marcos Silva",
        "contato": "7890-1234",
        "instagram": "@loja_g",
        "cidade": "Santo André",
        "bairro": "Vila Assunção",
        "rua": "Rua das Palmeiras, 404",
        "cep": "09030-310"
    },
    {
        "id": 8,
        "comercio": "Loja H",
        "segmento": "Móveis",
        "representante_ba": "Rep H",
        "responsável": "Julia Alves",
        "contato": "8901-2345",
        "instagram": "@loja_h",
        "cidade": "São Bernardo do Campo",
        "bairro": "Vila Euclides",
        "rua": "Rua Marechal Deodoro, 505",
        "cep": "09715-260"
    },
    {
        "id": 9,
        "comercio": "Loja I",
        "segmento": "Saúde",
        "representante_ba": "Rep I",
        "responsável": "Lucas Martins",
        "contato": "9012-3456",
        "instagram": "@loja_i",
        "cidade": "São Caetano do Sul",
        "bairro": "Olímpico",
        "rua": "Rua São Paulo, 606",
        "cep": "09520-200"
    },
    {
        "id": 10,
        "comercio": "Loja J",
        "segmento": "Livros",
        "representante_ba": "Rep J",
        "responsável": "Fernanda Costa",
        "contato": "0123-4567",
        "instagram": "@loja_j",
        "cidade": "Santo André",
        "bairro": "Parque das Nações",
        "rua": "Rua Japão, 707",
        "cep": "09210-110"
    }
]

export default cadastrosLeads;